name: Automatic Code Formatters
on: push

jobs:
  autoformat:
    name: Auto-format code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install formatters
        run: |
          sudo apt-get update
          sudo apt-get install black

      - name: Format code
        run: |
          black --target-version py36 --verbose --line-length 79 .

      - name: Commit changes
        uses: EndBug/add-and-commit@v6
        with:
          author_name: DistroBuildSync CI
          author_email: github-actions@github.com
          message: 'Code auto-formatting'
          add: -u
          signoff: true
          push: true
